### ISSUE TITLE
Deprecated Card Trading

### ISSUE THREAD

**Issue by rjswitzer3** [SoftwareTestingDomination/Domination#4]
# Deprecated Card Trading [MEDIUM]
## Forced trade-in of cards for troops

System occasionally forces the user to trade their cards for troops. Furthermore, the term forced is meant literally, for there is no other action that can be performed unless the trade is made. And on a side note, the AI players are never forced to trade and may retain their cards for an entire match.

**Comment by corbanmailloux** [comment]
After you have 5 cards in your hand, you must trade. This is in the rules located at: http://domination.sourceforge.net/applet/help/rules.htm
