### ISSUE TITLE
[N/A] Deprecated Player Appending

### ISSUE THREAD

**Issue by rjswitzer3** [SoftwareTestingDomination/Domination#8]
# Inability to Add Any Player [LOW]
## Deprecated Functionality
- Only local and network PC players can join game
- Mobile players can't join game

**Comment by corbanmailloux** [comment]
@rjswitzer3 Why did you close this? Could you just add a note here explaining (just for documentation purposes)?

**Comment by rjswitzer3** [comment]
Originally it did not appear possible to join a mobile user's game (and vice versa), but after further testing it was revealed that this was an inaccurate observation. Essentially, this should never have been logged as an issue and due to Github's lack of delete functionality, my only choice was to close this issue.
I will add 'N/A' to the title for clarification.
